
export const ADD_HOME_WORK_REQUEST="ADD_HOME_WORK_REQUEST" ;
export const ADD_HOME_WORK_SUCCESS="ADD_HOME_WORK_SUCCESS" ;
export const ADD_HOME_WORK_FAILURE="ADD_HOME_WORK_FAILURE" ;



export const ADD_TIME_TABLE_REQUEST="ADD_TIME_TABLE_REQUEST" ;
export const ADD_TIME_TABLE_SUCCESS="ADD_TIME_TABLE_SUCCESS" ;
export const ADD_TIME_TABLE_FAILURE="ADD_TIME_TABLE_FAILURE" ;



