
export const ADD_HOME_WORK_REQUEST="ADD_HOME_WORK_REQUEST" ;
export const ADD_HOME_WORK_SUCCESS="ADD_HOME_WORK_SUCCESS" ;
export const ADD_HOME_WORK_FAILURE="ADD_HOME_WORK_FAILURE" ;



export const ADD_TIME_TABLE_REQUEST="ADD_TIME_TABLE_REQUEST" ;
export const ADD_TIME_TABLE_SUCCESS="ADD_TIME_TABLE_SUCCESS" ;
export const ADD_TIME_TABLE_FAILURE="ADD_TIME_TABLE_FAILURE" ;







export const PAYMENT_HISTORY_REQUEST="PAYMENT_HISTORY_REQUEST" ;
export const PAYMENT_HISTORY_SUCCESS="PAYMENT_HISTORY_SUCCESS" ;
export const PAYMENT_HISTORY_FAILURE="PAYMENT_HISTORY_FAILURE" ;




export const HOMEWORK_DATA_REQUEST="HOMEWORK_DATA_REQUEST" ;
export const HOMEWORK_DATA_SUCCESS="HOMEWORK_DATA_SUCCESS" ;
export const HOMEWORK_DATA_FAILURE="HOMEWORK_DATA_FAILURE" ;



